/**
 * Typed access to the optimized station imagery (generated by scripts/optimize-images.mjs).
 * Provides AVIF/WebP/PNG source sets, blurred LQIP placeholders, and a dominant color
 * per image so cards/heroes can paint instantly and never flash empty.
 */

import manifest from './stationAssets.manifest.json';

export interface ImageFormats {
  avif?: string;
  webp?: string;
  png?: string;
}

export interface StationAsset {
  key: string;
  label: string;
  width: number;
  height: number;
  full: ImageFormats;
  hero: ImageFormats;
  wide: ImageFormats;
  square: ImageFormats;
  portrait: ImageFormats;
  /** Inline blurred placeholder (data: URI). */
  lqip: string;
  /** Dominant color hex, for skeletons / tints. */
  color: string;
}

export const stationAssets: Record<string, StationAsset> = manifest as Record<string, StationAsset>;

export const adminAsset: StationAsset | undefined = stationAssets['admin'];

export function assetForStation(stationNumber: number | string): StationAsset | undefined {
  return stationAssets[`station-${stationNumber}`];
}

export type AssetVariant = 'full' | 'hero' | 'wide' | 'square' | 'portrait';

/** Best available format url for a variant (prefers AVIF, then WebP, then PNG). */
export function bestSrc(asset: StationAsset | undefined, variant: AssetVariant): string | undefined {
  if (!asset) return undefined;
  const f = asset[variant];
  return f.avif ?? f.webp ?? f.png;
}
